### ISSUE TITLE
Wrong mathematics operation?

### ISSUE THREAD

**Issue by MaJerle** [littlefs-project/littlefs#546]
https://github.com/littlefs-project/littlefs/blob/1863dc7883d82bd6ca79faa164b65341064d1c16/lfs.c#L3498-L3500

Should we add either `8` or did you mix brackets?

**Comment by geky** [comment]
Hi @MaJerle, thanks for creating an issue.

I'm not exactly sure what the question is.

We subtract 2*4 from block_size because on average the overhead of CTZ skip-lists is 2 pointers (on disk pointers, which is 32-bits for littlefs). `0xffffffff / (lfs->cfg->block_size-2*4)` is then the maximum number of blocks a 32-bit CTZ skip-list could use, which is also the maximum number of pointers that a CTZ skip-list would ever need to store in a single block. Multiply by 4 again, since pointers are 32-bits, and the result is the largest amount of bytes used for metadata for any given 32-bit CTZ skip-list.

There's more detail here, which goes further into the math:
https://github.com/littlefs-project/littlefs/blob/master/DESIGN.md#ctz-skip-lists

For a 32-bit CTZ skip-list, it turns our the largest amount of bytes needed is 104 bytes, requiring a minimum block size of 104. Perhaps I should have just use that literal in the assert for clarity.
