### ISSUE TITLE
Comments on lfs_config struct fields do not describe bits vs. bytes

### ISSUE THREAD

**Issue by Jak-o-Shadows** [littlefs-project/littlefs#568]
The comments for the various size parameters in the _lfs_config_ struct do not describe whether they are in bytes vs. bits. This would help newcomers.

**Comment by geky** [comment]
Good point, will elaborate

**Comment by eclig** [comment]
What now?  Are they bytes or bits?

**Comment by geky** [comment]
Ah yes! My bad, I did not answer the actual question. I realize I still need to update this in the codebase but in the meantime:

All units are bytes.

---

Internally all units are bytes as well, it's fairly rare for the filesystem to operate on bits. One exception is the lookahead buffer, which is a bitmap containing one bit per block. Humorously it is the only field that mentions the unit in the documentation, because it is also configured in bytes. This was chosen for consistency.
