### ISSUE TITLE
used and free memory

### ISSUE THREAD

**Issue by stingdau1206** [littlefs-project/littlefs#980]
in file system info, i don't see value that show num of bytes is available, or num of bytes is used
how can i get it ?

**Comment by geky** [comment]
Hi @stingdau1206,

[`lfs_fs_size`](https://github.com/littlefs-project/littlefs/blob/d01280e64934a09ba16cac60cf9d3a37e228bb66/lfs.h#L718-L724) returns the number of blocks currently in use. If you multiply this by the block_size the result should be the number of bytes in use.

Because littlefs uses copy-on-write data-structures, the result may sometimes be larger than the actual usage, but it should never be smaller. Hopefully it's still useful for estimating how full the disk is.

**Comment by stingdau1206** [comment]
Hi @geky 
thanks for your reply, i'm Looking forward to a more detailed result about disk usage
but, after all, it will be ok for my case

**Comment by stingdau1206** [comment]
Hi @geky 
thanks for your reply, i'm Looking forward to a more detailed result about disk usage
but, after all, it will be ok for my case
